import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { authTables } from '@convex-dev/auth/server';

export default defineSchema({
  ...authTables,

  // `clientId` is a UUID generated by the client per row. Indexed by
  // [userId, clientId] so retried mutations resolve to the same server row
  // instead of creating duplicates (idempotency).
  expenses: defineTable({
    userId: v.id('users'),
    // Optional in the schema so legacy rows (pre-sync-layer) pass validation.
    // The `upsert`/`update`/`remove` mutations still require it via their
    // arg validators, so every NEW row gets one. Run convex/migrations to
    // backfill old rows; afterwards every row will have a clientId.
    clientId: v.optional(v.string()),
    amount: v.number(),
    currency: v.string(),
    type: v.union(v.literal('expense'), v.literal('income')),
    category: v.string(),
    merchant: v.string(),
    note: v.string(),
    date: v.string(),
    momoAccountId: v.optional(v.string()),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index('by_user', ['userId'])
    .index('by_user_and_date', ['userId', 'date'])
    .index('by_user_and_client', ['userId', 'clientId']),

  categories: defineTable({
    userId: v.id('users'),
    // Optional in the schema so legacy rows (pre-sync-layer) pass validation.
    // The `upsert`/`update`/`remove` mutations still require it via their
    // arg validators, so every NEW row gets one. Run convex/migrations to
    // backfill old rows; afterwards every row will have a clientId.
    clientId: v.optional(v.string()),
    name: v.string(),
    icon: v.string(),
    color: v.string(),
    isCustom: v.boolean(),
    createdAt: v.string(),
  })
    .index('by_user', ['userId'])
    .index('by_user_and_client', ['userId', 'clientId']),

  momoAccounts: defineTable({
    userId: v.id('users'),
    // Optional in the schema so legacy rows (pre-sync-layer) pass validation.
    // The `upsert`/`update`/`remove` mutations still require it via their
    // arg validators, so every NEW row gets one. Run convex/migrations to
    // backfill old rows; afterwards every row will have a clientId.
    clientId: v.optional(v.string()),
    provider: v.union(v.literal('mtn'), v.literal('telecel'), v.literal('airteltigo')),
    phoneNumber: v.string(),
    nickname: v.string(),
    linkedAt: v.string(),
  })
    .index('by_user', ['userId'])
    .index('by_user_and_client', ['userId', 'clientId']),

  pushSubscriptions: defineTable({
    endpoint: v.string(),
    keys: v.object({
      p256dh: v.string(),
      auth: v.string(),
    }),
    enabled: v.boolean(),
  })
    .index('by_endpoint', ['endpoint'])
    .index('by_enabled', ['enabled']),
});
